export const authors = [
 "Aldo Facho Dede",
 "Alexandra Ames",
 "Ale Costa",
 "Alfonso de la Torre",
 "Ana Loret de Mola",
 "Ana Lucía Mosquera Rosado",
 "Andrea Burga",
 "Augusto Townsend",
 "Matheus Calderón",
 "Brisa Deneumostier",
 "César Luna Victoria",
 "Claudia Cabieses",
 "Coco Luyo",
 "Daniela Meneses",
 "Diego Salazar",
 "Elías Neira",
 "Farid Kahhat",
 "Gabriela Rodríguez",
 "Gonzalo Banda",
 "Guillermo Flores Borda",
 "Javier Albán",
 "Jorge Lazarte",
 "Kenneth Sánchez",
 "Leah Sacín",
 "Liliana Checa",
 "Luis Villacorta",
 "Mariana Alegre",
 "Mario Zúñiga",
 "Marisol Cuellar",
 "Maurizzio Zamudio",
 "Milagros Campos",
 "Alejandra Ruiz León",
 "Natalia Ames",
 "Oswaldo Molina",
 "Paola del Carpio",
 "Roberto Brañez",
 "Roberto Castro",
 "Valeria Aron",
 "Vania García"]