export const preferences = {
 categories: [
  "Caja de herramientas para pensar en la política",
  "Ciudades cómo vamos",
  "Ciudades que inspiran",
  "Colores en audio",
  "Conexión Jaguar",
  "Divina política",
  "Después de la doce",
  "El derecho al revés",
  "El modelo económico explicado",
  "El podcast de noticias de Augusto Townsend",
  "El podcast económico de Ale Costa",
  "El sur antisistema",
  "Escena Internacional",
  "Escena Internacional con Farid Kahhat",
  "Espacio mindfulness",
  "Hablemos de migración",
  "Hablemos de política",
  "Hora Libre",
  "Literatura para peatones",
  "La mala sangre",
  "La noticia del día explicada",
  "Lectura de juego",
  "Los Aprendedores",
  "Lugar reservado",
  "Más allá de lo evidente",
  "Más allá de la polémica",
  "Miércoles de debate",
  "Oído a los datos",
  "Opción pública",
  "Perú sin barreras",
  "Propuestas del Bicentenario",
  "Podcasts Especiales",
  "Siempre en campaña",
  "Sin ciencia no hay futuro",
  "Trasciende",
  "Una politóloga te cuenta",
  "Verde en valor",
  "Ventaja cooperativa",
  "Voceras"
 ],
}